# compose.yaml

name: LatexProgect

services:
  latex:
    # コンテナ名
    container_name: ${CONTAINER_NAME}

    # Dockerfileを使ってbuildする
    build:
      context: .
      dockerfile: ./Dockerfile
    
    volumes:
      - .:/work

    working_dir: /work
    
    command: >
      bash
    tty: true