# compose.yaml

name: LatexProgect

services:
  latex:
    # コンテナ名
    container_name: ${CONTAINER_NAME}

    # Dockerfileを使ってbuildする
    build:
      context: .
      dockerfile: ./Dockerfile
      #args:
      #  USERNAME: $(USERNAME)
      # target: dev

    # ビルドされたイメージのタグ
    # 今回は個人ようなのでimage名を変更しない
    # image: ${HOST_NAME}/${SERVICE_NAME}:${VERSION}
    
    volumes:
      - .:/work

    working_dir: /work

    # ボリュームマウント
    #volumes:
    #  - ./src:/home/texlive/src
      #- ./.vscode-server:/home/texlive/.vscode-server
    
    command: >
      bash
    tty: true