# compose.yaml

name: LaTexProgect

services:
  latex:
    # コンテナ名
    container_name: texlive

    # Dockerfileを使ってbuildする
    build:
      context: .
      dockerfile: ./Dockerfile

    # 全体をボリュームにマウント    
    volumes:
      - .:/work

    # コンテナでのカレントディレクトリ指定
    working_dir: /work

    # ターミナル設定
    command: >
      bash
    tty: true
